// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class last_changes_for_mesaj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(last_changes_for_mesaj));
        
        string IMigrationMetadata.Id
        {
            get { return "202209250740478_last_changes_for_mesaj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
